name: Run Globoplay M3U Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_playlist:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp requests

    - name: Download cookies
      run: |
        curl -o cookies.txt ${{ secrets.COOKIES_URL }}

    - name: Generate M3U Playlist
      run: |
        python generate_m3u.py

    - name: Upload M3U Playlist
      uses: actions/upload-artifact@v2
      with:
        name: playlist
        path: ./PLAYLIST.m3u
