name: Run Globoplay M3U Generator

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests

      - name: Download cookies from secret URL
        run: |
          curl -L -o cookies.txt "${{ secrets.COOKIES_URL }}"

      - name: Run M3U playlist generator script
        run: |
          python generate_m3u.py cookies.txt

      - name: Upload M3U Playlist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playlist
          path: ./PLAYLIST.m3u
