name: Run M3U Generator

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora (minuto 0 de cada hora)

jobs:
  generate_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # necessário para permitir commits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        id: install_deps
        run: |
          python -m pip install --upgrade pip
          
          # Lista de pacotes PyPI conhecidos que têm nomes de importação diferentes
          declare -A MODULE_TO_PACKAGE
          MODULE_TO_PACKAGE["bs4"]="beautifulsoup4"
          MODULE_TO_PACKAGE["yaml"]="PyYAML"
          # Adicione mais traduções aqui se necessário
          
          # Lista de módulos que geralmente são pacotes PyPI e estavam no original
          # Incluímos 'beautifulsoup4' diretamente para garantir a instalação correta de 'bs4'
          PACKAGES_TO_INSTALL="yt-dlp requests beautifulsoup4"

          # Tenta analisar o arquivo portugal.py para encontrar outros imports
          if [ -f portugal.py ]; then
            # Lista de módulos padrão do Python que NÃO precisam ser instalados:
            STANDARD_MODULES="os|sys|json|re|time|datetime|pathlib|logging|collections|io|math|random|csv|sqlite3|threading|multiprocessing|argparse|socket|http|urllib|xml|html|ftplib|smtplib|poplib|imaplib|ssl|hashlib|base64|zlib|gzip|zipfile|tarfile"
            
            # Extrai imports de 'import X' e 'from X import Y'
            # 1. 'import X' -> captura X
            # 2. 'from X import Y' -> captura X
            ADDITIONAL_PACKAGES=$(grep -E '^\s*(import\s+|from\s+)[a-zA-Z0-9_]+' portugal.py | \
                                 awk '{
                                   if ($1 == "import") {
                                     print $2
                                   } else if ($1 == "from") {
                                     print $2
                                   }
                                 }' | \
                                 sed 's/,//g' | \
                                 grep -vE "^($STANDARD_MODULES)$" | \
                                 tr '\n' ' ')
                                 
            PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL $ADDITIONAL_PACKAGES"
            
            # Processa a lista final para aplicar as traduções
            FINAL_PACKAGES=""
            for module in $PACKAGES_TO_INSTALL; do
              # Verifica se o módulo tem uma tradução conhecida
              if [[ -n "${MODULE_TO_PACKAGE[$module]}" ]]; then
                FINAL_PACKAGES+="${MODULE_TO_PACKAGE[$module]} "
              else
                FINAL_PACKAGES+="$module "
              fi
            done
            
            # Remove duplicatas e espaços extras
            FINAL_PACKAGES=$(echo $FINAL_PACKAGES | tr ' ' '\n' | sort -u | tr '\n' ' ')
            
            echo "Pacotes identificados para instalação: $FINAL_PACKAGES"
            
            if [ -n "$FINAL_PACKAGES" ]; then
              pip install $FINAL_PACKAGES
            else
              echo "Nenhum pacote PyPI não-padrão identificado para instalação."
            fi
          else
            echo "Arquivo portugal.py não encontrado. Instalando apenas yt-dlp, requests e beautifulsoup4 como fallback."
            pip install $PACKAGES_TO_INSTALL
          fi

      - name: Download cookies from secret URL
        run: |
          curl -L -o cookies.txt "${{ secrets.COOKIES_URL }}"

      - name: Run M3U playlist generator script
        run: |
          python portugal.py cookies.txt

      - name: Commit and push updated PLAYLIST.m3u
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add PLAYLIST.m3u
          
          if git diff --cached --quiet; then
            echo "Nenhuma mudança em PLAYLIST.m3u"
          else
            git commit -m "Atualiza PLAYLIST.m3u via GitHub Actions"
            git push
          fi
